# Generated by Django 4.0.1 on 2022-01-19 06:48

from django.db import migrations, models



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stone_type', models.CharField(max_length=255)),
                ('discovery_license_number', models.CharField(max_length=255)),
                ('operating_license_number', models.CharField(max_length=255)),
                ('minimum_operating_tonnage', models.PositiveBigIntegerField()),
                ('government_law', models.PositiveIntegerField()),
                ('issue_date', models.DateField()),
                ('province', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('village', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
